[phases.build]
cmds = [
    "cd frontend && npm install --force --legacy-peer-deps && npm run build",
    "cd backend && npm install --force --legacy-peer-deps"
]

[phases.setup]
nixPkgs = ["nodejs_20"]

[start]
cmd = "npm start"
