[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.build]
cmds = [
    "cd frontend && npm install --force --legacy-peer-deps && npm run build",
    "cd backend && npm install --force --legacy-peer-deps",
    "cd admin/backend && npm install --force --legacy-peer-deps"
]

[start]
cmd = "node railway-monorepo.js"
